#
#     Copyright (c) 2018 Orange
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

### Create REJECTED
POST  {{serviceOrder.url}}/serviceOrder
    ?fields=id,state,description,relatedParty.id,toto
Accept: application/json
Content-Type: application/json

< ./json/serviceOrder_create_in_rejected.json

### Create COMPLETED
POST  {{serviceOrder.url}}/serviceOrder
    ?fields=id,state,description,relatedParty.id,toto
Accept: application/json
Content-Type: application/json

< ./json/serviceOrder_create_in_completed.json

### List
GET  {{serviceOrder.url}}/serviceOrder/
Accept: application/json

### List with fields
GET  {{serviceOrder.url}}/serviceOrder
    ?fields=id,state,description,relatedParty.id
Accept: application/json

### List COMPLETED
GET  {{serviceOrder.url}}/serviceOrder
    ?state=COMPLETED
Accept: application/json