#
#     Copyright (c) 2018 Orange
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

version: "3"
services:
  mongo:
    image: mongo:3
    restart: always
    volumes:
      - /var/lib/mongo
    command: --smallfiles

  mariadb:
    image: mariadb:10
    restart: always
    volumes:
      - /var/lib/mariadb
    environment:
      MYSQL_DATABASE: nbi
      MYSQL_PASSWORD: toto
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: rene
# APP  ***************************************************************************************
  nbi:
    build: .
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/nbi
      SPRING_DATASOURCE_PASSWORD: toto
      SPRING_DATASOURCE_USERNAME: rene
      SPRING_DATA_MONGODB_HOST: mongo
      SDC_HOST: http://${SDC_IP}:8080
      AAI_HOST: https://${AAI_IP}:8443
      SO_HOST: http://${SO_IP}:8080
    restart: on-failure
    depends_on:
      - mariadb
      - mongo
      - msb_discovery

# MSB  ***************************************************************************************
  msb_consul:
    image: consul:0.9.3
    restart: always
    ports:
      - 8500:8500

  msb_discovery:
    image: nexus3.onap.org:10001/onap/msb/msb_discovery
    restart: always
    environment:
      CONSUL_IP: msb_consul
    ports:
      - 10081:10081
    depends_on:
      - msb_consul

  msb_apigateway:
    image: nexus3.onap.org:10001/onap/msb/msb_apigateway
    restart: always
    environment:
      CONSUL_IP: msb_consul
      SDCLIENT_IP: msb_discovery
      ROUTE_LABELS: "visualRange:1"
      UPSTREAM_DNS_SERVERS: 127.0.0.11
    ports:
      - 80:80
    depends_on:
      - msb_discovery
      - msb_consul