/*
 * API ServiceOrder
 * serviceOrder API designed for ONAP Beijing Release. This API is build from TMF open API16.5 + applied TMF guideline 3.0
 *
 * OpenAPI spec version: 0.1.1_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.onap.nbi.apis.serviceorder.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * Used to defined a place useful for the service (for example a delivery geographical place)
 */
@ApiModel(description = "Used to defined a place useful for the service (for example a delivery geographical place)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-02-19T14:00:30.767Z")
public class Place {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("href")
    private String href = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("role")
    private String role = null;

    @JsonProperty("@referredType")
    private String referredType = null;

    @JsonProperty("@schemaLocation")
    private String schemaLocation = null;

    public Place id(String id) {
        this.id = id;
        return this;
    }

    /**
     * @return id
     **/
    @JsonProperty("id")
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Place href(String href) {
        this.href = href;
        return this;
    }

    /**
     * Reference of a place (for instance in google map)
     *
     * @return href
     **/
    @JsonProperty("href")
    @ApiModelProperty(value = "Reference of a place (for instance in google map)")
    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public Place name(String name) {
        this.name = name;
        return this;
    }

    /**
     * @return name
     **/
    @JsonProperty("name")
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Place role(String role) {
        this.role = role;
        return this;
    }

    /**
     * The role of the place (e.g. delivery address, install site etc)
     *
     * @return role
     **/
    @JsonProperty("role")
    @ApiModelProperty(required = true, value = "The role of the place (e.g. delivery address, install site etc)")
    @NotNull
    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Place referredType(String referredType) {
        this.referredType = referredType;
        return this;
    }

    /**
     * @return referredType
     **/
    @JsonProperty("@referredType")
    @ApiModelProperty(value = "")
    public String getReferredType() {
        return referredType;
    }

    public void setReferredType(String referredType) {
        this.referredType = referredType;
    }

    public Place schemaLocation(String schemaLocation) {
        this.schemaLocation = schemaLocation;
        return this;
    }

    /**
     * @return schemaLocation
     **/
    @JsonProperty("@schemaLocation")
    @ApiModelProperty(value = "")
    public String getSchemaLocation() {
        return schemaLocation;
    }

    public void setSchemaLocation(String schemaLocation) {
        this.schemaLocation = schemaLocation;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Place place = (Place) o;
        return Objects.equals(this.id, place.id) &&
                Objects.equals(this.href, place.href) &&
                Objects.equals(this.name, place.name) &&
                Objects.equals(this.role, place.role) &&
                Objects.equals(this.referredType, place.referredType) &&
                Objects.equals(this.schemaLocation, place.schemaLocation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, href, name, role, referredType, schemaLocation);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Place {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    href: ").append(toIndentedString(href)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    referredType: ").append(toIndentedString(referredType)).append("\n");
        sb.append("    schemaLocation: ").append(toIndentedString(schemaLocation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

