@startuml

enum EventType {
   ServiceOrderCreationNotification
   ServiceOrderStateChangeNotification
   ServiceOrderItemStateChangeNotification
}

class ErrorRepresentation {
   code:int
   reason:string
   message:string
   status:int
   referenceError:string
   @type:string
   @schemaLocation:string
}

class Listener {
   eventId:string
   eventDate:dateTime
   event:object
}
   Listener --> "1-1" EventType : eventType

@enduml